/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.leofabris.icoViewer;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.sf.image4j.codec.ico.ICOEncoder;

/**
 *
 * @author leonardo.fabris
 */
public class PNGtoICOUnico extends javax.swing.JInternalFrame {

    BufferedImage bi;
    String nomeArquivo;
    
    /**
     * Creates new form PNGtoICOUnico
     */
    public PNGtoICOUnico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLocalIcone = new javax.swing.JTextField();
        btnSelIcone = new javax.swing.JButton();
        labelIcone = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Converter PNG para ICO");

        jLabel1.setText("Caminho do ícone:");

        btnSelIcone.setText("...");
        btnSelIcone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelIconeActionPerformed(evt);
            }
        });

        labelIcone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setText("Converter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocalIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelIcone)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelIcone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLocalIcone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelIcone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelIconeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelIconeActionPerformed
        JFileChooser seleciona = new JFileChooser();
        seleciona.setDialogTitle("Selecione o arquivo do ícone");
        seleciona.setDialogType(JFileChooser.OPEN_DIALOG);
        seleciona.setFileSelectionMode(JFileChooser.FILES_ONLY);
        seleciona.setMultiSelectionEnabled(false);
        seleciona.showOpenDialog(this);

        try {
            txtLocalIcone.setText(seleciona.getSelectedFile().getAbsolutePath());
            
            labelIcone.setIcon(new ImageIcon(txtLocalIcone.getText()));
            
            bi = ImageIO.read(seleciona.getSelectedFile());
            
            nomeArquivo = seleciona.getSelectedFile().getName();
            
        } catch (NullPointerException ex) {
            System.out.println("Nada selecionado...");
        } catch (IOException ex) {
            System.out.println("Erro ao ler o arquivo de imagem...");
        }

    }//GEN-LAST:event_btnSelIconeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            ICOEncoder.write(bi, new File(System.getProperty("user.home") + File.separator + "Desktop" + File.separator + nomeArquivo.replaceAll(".png", ".ico")));
            JOptionPane.showMessageDialog(null, "Arquivo exportado com sucesso!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao converter o arquivo:\n\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelIcone;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelIcone;
    private javax.swing.JTextField txtLocalIcone;
    // End of variables declaration//GEN-END:variables
}
